# single_channel_config.yaml

path:
  dataset: "C:/Users/kataoka-lab/Desktop/sound_data/mix_data/dataset_1ch_random_rt60_snr_v1/train.csv"
  validation: "C:/Users/kataoka-lab/Desktop/sound_data/mix_data/dataset_1ch_random_rt60_snr_v1/val.csv"
  output: "C:/Users/kataoka-lab/Desktop/Conv-TasNet/RESULT/pth/DEMAND_DEMAND_1ch/ConvTasNet_noise_only"

dataset:
  target: "clean"
  input: "noise_only"



model:
  channels: 1
  type: "enhance"

training:
  epochs: 100
  batch_size: 16
  accumulation_steps: 1
  learning_rate: 0.001
  loss_function: "stftMSE"
  amp: true
  early_stopping:
    enabled: true
    patience: 10

resume_checkpoint: null